### PR TITLE
add mcr to ahk converter

### PR DESCRIPTION
**Pull request by Z12aS**
does as much as possible
and images aren't possible xd

### CODE REVIEW

**Comment by yesyesyes69** [comment]
oh also it doesnt use the functions.ahk coz am pro

**Review by FaethyvveIcye — CHANGES_REQUESTED** [review]
`KeyPress` in JitBits Macro Recorder and `Send` in AHKscript behave differently, thus the implementation of the similarly named `KeyPress()` present in `functions.ahk`

Additionally, without any dependency, this may also be better suited as an independent project

**Comment by Z12aS** [comment]
good?

**Comment by yesyesyes69** [comment]
forgot to add the `n there lmao

**Comment by yesyesyes69** [comment]
im a monkey and forgot mouse commands

**Comment by FaethyvveIcye** [comment]
This does not properly implement `KeyPress()` syntax to pass strings as paramters, does not handle non-letter keys properly. It also does not properly implement the native `ImageSearch` function either. There are more errors and the output code readability is bad. I believe this may be better suited as an independent project.

**Comment by Z12aS** [comment]
i don't wanna be toxic but lets see you implementing the native `ImageSearch`
firstly its split into multiple lines and the converter works line per line
and second its in a pixel by pixel format i don't know how to convert

for the `KeyPress()`, i think you mean i need to add a default delay like 50 ms or something

**Pull request closed without merging**
